### ISSUE TITLE
UNMET PEER DEPENDENCY laravel-mix@1.7.2, mix.extend is not a function

### ISSUE THREAD

**Issue by polearnik** [Elhebert/laravel-mix-sri#1]
Hi Im using laravel 5.5 
on install I have error UNMET PEER DEPENDENCY laravel-mix@1.7.2 
and on run npm run dev it show TypeError: mix.extend is not a function

I see in package.json I have dependency  "laravel-mix": "^1.0",

and in webpack.mix.js I have
```
let mix = require('laravel-mix');
require('laravel-mix-sri')
mix.styles([
        "public/css/application.css",
    ], 'public/css/all.css')
    .generateIntegrityHash();
```

**Comment by Elhebert** [comment]
Hi,

It requires Laravel 2.1.2 and above. Because you are running a lower version of mix, it fails.

I'll document this in the README 👌
