### ISSUE TITLE
Can not use this with OctoberCMS

### ISSUE THREAD

**Issue by emzet** [Elhebert/laravel-mix-sri#14]
If tried to use this package within **OctoberCMS** (built on Laravel), it does not work due to hardcoded paths of:

`assets` -> `public${asset}`
`mix-sri.json` -> `public/mix-sri.json`

In `webpack.mix.js` one can use `setPublicPath('foo/bar')`, so this `publicPath` value should be used then by this extension.

**Comment by Elhebert** [comment]
closed in #13
