### ISSUE TITLE
dont fill mix-sri.json

### ISSUE THREAD

**Issue by polearnik** [Elhebert/laravel-mix-sri#2]
Hi.
I try to use this plugin in this mode 
```javascript
mix.scripts([
        "public/lib/socket.io/socket.io.js",
        "public/js/datafeed.js",
        "public/js/web.js",
    ], 'public/build/js/web_all.js')
    .generateIntegrityHash();
// this also not work
mix.generateIntegrityHash();
```
but file public/mix-sri.json is empty
```javascript
{}
```
I try to debug and find stats.toJson().assetsByChunkName return an empty object
If i change code 
```javascript
let assets = Object.assign({}, stats.toJson().assetsByChunkName)
```
 to 
```javascript
 let assets = stats.toJson().assets.map(asset => {
                return asset.name;
            });
```
it start to work 
```javascript
mix.scripts([
        "public/lib/socket.io/socket.io.js",
        "public/js/datafeed.js",
        "public/js/web.js",
    ], 'public/build/js/web_all.js')
    .generateIntegrityHash();
// and in this mode work too
mix.generateIntegrityHash();
```

**Comment by Elhebert** [comment]
Can you give me more information on your setup?

I don't have any issues using the latest version of Laravel Mix (2.1.11 at this point). Both on my local environment (Mac OsX High Sierra, npm 8) and in production (Debian 9, npm 8).

If it's, indeed, a problem coming from the environment, I might have to change the way I'm getting the assets from webpack.

**Comment by polearnik** [comment]
if i try example from readme with 
```
mix.js('src/app.js', 'dist')
   .generateIntegrityHash()
```
it work. But if I use 
```
mix.scripts([
        "public/lib/socket.io/socket.io.js",
        "public/js/datafeed.js",
        "public/js/web.js",
    ], 'public/build/js/web_all.js')
    .generateIntegrityHash();
// this also not work
mix.generateIntegrityHash();
```
not work.
What information you need?

**Comment by polearnik** [comment]
Linux mint 18.3 KDE 
node v6.13.1
npm 3.10.10
laravel-mix@2.1.11

hmm. Maybe node is old version? Now I try  to update node to latest version and edit my responce

**Comment by Elhebert** [comment]
It's probably the source of the issue 🤔 

I'll check if there's a better way to get the assets than what I'm actually doing. Otherwise, I'll force node 8 as a requirement.

**Comment by polearnik** [comment]
I update node to 9.9.0 and npm was updated to  5.8.0
also it was asking for install + ajv@6.4.0
+ ajv-keywords@3.1.0 and i instal this version 

in webpack.js
```
mix.styles([
        "public/css/application.css",
        // "public/css/bootstrap.min.css",
    ], 'public/build/css/all.css')
    .generateIntegrityHash({
        enabled: true
    });


mix.generateIntegrityHash({
    enabled: true
});
mix.scripts([
        "public/lib/socket.io/socket.io.js",
        "public/js/datafeed.js",
        "public/js/web.js",
    ], 'public/build/js/web_all.js')
    .generateIntegrityHash({
    enabled: true
});
```

no changes  mix-sri.json have an empty object

**Comment by polearnik** [comment]
Hi Any updates? Did you try to use .scripts() method instead of .js()?

**Comment by Elhebert** [comment]
Hi @polearnik,

I did a quick check, you can't use `scripts()` with this.

`scripts()` is not using webpack, thus, not using this plugin.

**Comment by Gummibeer** [comment]
I have the same issue with a custom webpack-plugin - I don't get my assets into a chunk (have no idea how to and after 2h googleing I don't have found a hint ...).
The PR #3 by @polearnik fixed my problem! :)

**Comment by Gummibeer** [comment]
Ok, it fixed my custom plugin but destroyed the normal sass one. webpack adds `?hash` to the filepath - this isn't resolvable in a normal filesystem ...
