### ISSUE TITLE
Include type definitions, please

### ISSUE THREAD

**Issue by bram-pkg** [Elhebert/laravel-mix-sri#29]

**Comment by Elhebert** [comment]
Hello,

What would be the use case here?
The component has only 2 configuration options, and one is optional: 
```
{
  enable: boolean
  algorithm: string
}
```

Feel free to create a PR that would handle the generation of a index.d.ts with the proper types.

**Comment by bramceulemans** [comment]
Autocompletion on the laravel-mix object

**Comment by Elhebert** [comment]
You are welcome to submit a PR that will add the proper types for that.

**Comment by bramceulemans** [comment]
I'll look into it!
