### ISSUE TITLE
TypeScript is not compiled when installing through npm

### ISSUE THREAD

**Issue by 26** [Elhebert/laravel-mix-sri#35]
It seems that the TypeScript code is not compiled after installing the package through npm. I had to manually compile the TypeScript code, otherwise `mix` would terminate with the following exception:

```
Error: Cannot find module './node_modules/laravel-mix-sri/build/index.js'. Please verify that the package.json has a valid "main" entry
```

**Comment by Elhebert** [comment]
Oh, that's annoying. I probably forgot to run the build command before pushing the code to NPM 😱

Will fix that!

Thanks for reporting.
