### ISSUE TITLE
Seems to only work on .sass and even then a bit dodgy?

### ISSUE THREAD

**Issue by themuddfamily** [Elhebert/laravel-mix-sri#36]
Hey,

Currently using:
Node v14.18.1
NPM 6.14.15
laravel-mix 6.0.6
laravel-mix-sri 1.0.5

Im currently having an issue where the .generateIntegrityHash(); function only seems to work on .sass files - for example:
```
mix.sass('resources/assets/sass/app.scss', 'public/css/app.css').generateIntegrityHash();
```
works just fine - results in:
```
{
    "/css/app.css": "sha256-GrWPKJHfEJ46ucNa/5Qeinr+o327K6tzbsf10y/ASg4="
}
```
in mix-sri.json

But pretty much all other situations it does not seem to work

```
    mix.styles([
        bowerDir + 'font-awesome/css/font-awesome.css',
        bowerDir + 'bootstrap-datepicker/dist/css/bootstrap-datepicker.css',
        'public/build/css/timepicker.css',
        bowerDir + 'video.js/dist/video-js.css'
    ], 'public/css/vendor.css').generateIntegrityHash();
```
Does not produce an error on build but theres no vendor.css at all in mix-sri.json

Same with more complex examples like this:
```
mix.sass(fontendDir + 'css/frontend.scss', 'public/css/frontend.css').after(() => {
    mix.styles([
        nodeDir + 'owl.carousel/dist/assets/owl.carousel.css',
        'public/frontend/css/frontend.css',
    ], 'public/frontend/css/app.css').generateIntegrityHash();
});
```

and I haven't been able to get any JS hashes to generate for example:

```
mix.scripts([
    bowerDir + 'xdomain/dist/xdomain.js'
], 'public/js/xdomain.js').generateIntegrityHash();
```

----------

It would be useful if we could pass file names into the function directly such as this?
`mix.generateIntegrityHash(['public/css/vendor.css']);`

**Comment by themuddfamily** [comment]
@Elhebert 

This is a private bitbucket repo but all of these show in the output (and are correctly output) by laravel-mix

![image](https://user-images.githubusercontent.com/1263618/138256228-6b4a3bd5-d6dc-421c-8e7b-a6b6b5ec5ebf.png)

I also have the same issue with .less, .version, .copy - sass is the only working function?

Ill get you an example on a brand new repo if required. No problem

**Comment by Elhebert** [comment]
I'll investigate tonight, but if you could provide a repo with a proper example that be great. Would help to identify the exact problem. But I'll do my best without if it's too hard to provide something as you need to strip out all the proprietary code.

**Comment by themuddfamily** [comment]
@Elhebert 

https://github.com/themuddfamily/laravel-mix-sri-broken-example

All it should require is `yarn` and `yarn run prod`
