### ISSUE TITLE
Production mode compilation not working after update

### ISSUE THREAD

**Issue by bram-pkg** [Elhebert/laravel-mix-sri#38]
It seems like it's not stripping the version hashes properly.

```
Error: ENOENT: no such file or directory, open '/var/www/html/public/fonts/vendor/bootstrap-icons/bootstrap-icons.woff?67475f65d9d8a1fe03a2501298bdf929'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at /var/www/html/node_modules/laravel-mix-sri/build/SriPlugin.js:33:50
    at Array.forEach (<anonymous>)
    at process (/var/www/html/node_modules/laravel-mix-sri/build/SriPlugin.js:23:18)
    at _next1 (eval at create (/var/www/html/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:37:1)
    at eval (eval at create (/var/www/html/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:60:1) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/var/www/html/public/fonts/vendor/bootstrap-icons/bootstrap-icons.woff?67475f65d9d8a1fe03a2501298bdf929'
}
```

**Comment by Elhebert** [comment]
🤔 Was this working before I made the change to using `assets` instead of `assetsByChunkName`? Not sure how that change impact the cache busting part.

AFAIK the cache busting feature of mix only adds an `?id=<random-20-char-string>` to assets path.

**Comment by bram-pkg** [comment]
> AFAIK the cache busting feature of mix only adds an ?id=<random-20-char-string> to assets path.

Fonts apperantly don't they just get `\?\w{32}` for some reason.

**Comment by bram-pkg** [comment]
I know it was working on the previous release and not on the latest one.

**Comment by Elhebert** [comment]
I'll try to reproduce the issue tonight locally to see what's the best way to fix this.

**Comment by Elhebert** [comment]
@bram-pkg could you share what your mix config looks like? Or even better share a repo that I can use to reproduce the issue.

**Comment by bram-pkg** [comment]
https://gitlab.com/rijnijssel/sdxam

There you go.

**Comment by Elhebert** [comment]
Based on my tests the issue is that bootstrap is loading fonts in your css. Thus appearing in Webpack assets. But theses fonts are inside your CSS, so we should ignore them.

I did some quick testing and I think I've got a solution. I'll do some tests and will create PR later.

**Comment by bram-pkg** [comment]
Damn, that sounds like a really obscure issue 😅

**Comment by Elhebert** [comment]
@bram-pkg I made a PR. Hopefully it'll solve the issue without adding side effects.

**Comment by Elhebert** [comment]
[v1.0.7](https://github.com/Elhebert/laravel-mix-sri/releases/tag/1.0.7) is out. It should fix the issue.

**Comment by bram-pkg** [comment]
Thank you Dieter!
