### ISSUE TITLE
Filter cache buster parameters from webpack output files

### ISSUE THREAD

**Issue by romanzipp** [Elhebert/laravel-mix-sri#7]
I'm using Laravel Mix with webpack's code splitting feature.

```js
mix.webpackConfig({
    output: {
        chunkFilename: 'js/app.[name].js?id=[chunkhash]'
    }
});

mix.version();
mix.generateIntegrityHash({ enabled: true });

mix.js('resources/js/app/app.js', 'public/js/app.js');
```

The files outputted by webpack - of course - are not containing the cache buster value in the filename, but it's outputted to the compiled `app.js`. 

The laravel-mix-sri package is trying to read the chunk output files with the `id` parameter:

```
Error: ENOENT: no such file or directory, open '/.../public/js/app.components.js?id=2fa6dca55e911eae4a74'
```

It would be good to filter out any parameters after receiving the oputput files list from webpack.

**Comment by Elhebert** [comment]
I need to take a look at how the mix-manifest.json deals with this issue to see what we can do to handle this.
